/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package de.drl.de_routing;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int accept_button=0x7f020000;
        public static final int icon=0x7f020001;
        public static final int play_button=0x7f020002;
        public static final int record_button=0x7f020003;
        public static final int reset_button=0x7f020004;
        public static final int splash=0x7f020005;
    }
    public static final class id {
        public static final int acceptButton=0x7f060005;
        public static final int button1=0x7f060002;
        public static final int button2=0x7f060003;
        public static final int playButton=0x7f060001;
        public static final int recordButton=0x7f060000;
        public static final int restartButton=0x7f060004;
    }
    public static final class layout {
        public static final int activity_sound_recorder=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
    }
    public static final class xml {
        public static final int config=0x7f040000;
    }
}
